services:
  headscale:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: headscale
    restart: unless-stopped
    command: serve
    volumes:
      - headscale_data:/var/lib/headscale
      - ./config.yaml:/etc/headscale/config.yaml:ro

volumes:
  headscale_data:
