services:
  headscale:
    image: headscale/headscale:0.23.0
    container_name: headscale
    restart: unless-stopped
    command: serve
    volumes:
      - headscale_data:/var/lib/headscale
      - ./config.yaml:/etc/headscale/config.yaml:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.headscale.rule=Host(`dgx.m2informatica.es`)"
      - "traefik.http.routers.headscale.entrypoints=websecure"
      - "traefik.http.routers.headscale.tls.certresolver=letsencrypt"
      - "traefik.http.services.headscale.loadbalancer.server.port=8080"

volumes:
  headscale_data:
